// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZxsC9EYEfDR8bOZldkIovRkjl2tZ9Ac',
    appId: '1:317600481828:android:5a336043158c456fbf4eb1',
    messagingSenderId: '317600481828',
    projectId: 'healthvault-a9e08',
    storageBucket: 'healthvault-a9e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5u7lu6qDV99_3J-D8tFA-FAll3GPny8',
    appId: '1:317600481828:ios:571c33906d064040bf4eb1',
    messagingSenderId: '317600481828',
    projectId: 'healthvault-a9e08',
    storageBucket: 'healthvault-a9e08.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPOf-uTKAZLfaUwbt-nMaevFyp1qDm3w',
    appId: '1:317600481828:web:a810f833d239c35cbf4eb1',
    messagingSenderId: '317600481828',
    projectId: 'healthvault-a9e08',
    authDomain: 'healthvault-a9e08.firebaseapp.com',
    storageBucket: 'healthvault-a9e08.firebasestorage.app',
    measurementId: 'G-HZSY9FCG9Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5u7lu6qDV99_3J-D8tFA-FAll3GPny8',
    appId: '1:317600481828:ios:571c33906d064040bf4eb1',
    messagingSenderId: '317600481828',
    projectId: 'healthvault-a9e08',
    storageBucket: 'healthvault-a9e08.firebasestorage.app',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPOf-uTKAZLfaUwbt-nMaevFyp1qDm3w',
    appId: '1:317600481828:web:4f55d2afbc2ed066bf4eb1',
    messagingSenderId: '317600481828',
    projectId: 'healthvault-a9e08',
    authDomain: 'healthvault-a9e08.firebaseapp.com',
    storageBucket: 'healthvault-a9e08.firebasestorage.app',
    measurementId: 'G-KVZP64B72T',
  );

}